// Command licensegen generates THIRD_PARTY_LICENSES, the attribution bundle
// shipped alongside every ofga artifact. MIT, BSD and Apache-2.0 all require
// reproducing their notices when distributing in binary form, and the ofga
// binary statically links well over a hundred such modules.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strings"

	"github.com/google/licensecheck"
)

// allowed is the set of licenses ofga may ship. All are permissive and satisfied
// by reproducing their notice, which is exactly what this bundle does. Anything
// else — copyleft, or text licensecheck cannot identify — needs a human to look
// at it before it reaches a release, so it fails the build instead.
var allowed = map[string]bool{
	"Apache-2.0":   true,
	"BSD-2-Clause": true,
	"BSD-3-Clause": true,
	"ISC":          true,
	"MIT":          true,
}

// exceptions records licenses permitted for one specific module, and why. Kept
// per module rather than folded into allowed so that the next dependency
// arriving under the same license still fails and gets its own look.
var exceptions = map[string]struct {
	ids    []string
	reason string
}{
	"github.com/opencontainers/go-digest": {
		ids:    []string{"CC-BY-SA-4.0"},
		reason: "CC-BY-SA-4.0 applies to LICENSE.docs, which covers that repository's prose documentation only. ofga links the Apache-2.0 code and vendors none of the docs.",
	},
}

// module is one dependency linked into the ofga binary.
type module struct {
	Path    string
	Version string
	Dir     string
}

// mainModule is this repository's own module path, excluded from its own bundle.
const mainModule = "github.com/sergiught/openfga-cli"

type target struct{ goos, goarch string }

// releaseTargets mirrors the goos/goarch matrix in .goreleaser.yaml. Build
// constraints make the linked module set platform-specific — purego is reachable
// only on darwin — so the bundle is the union across every platform we release,
// not just whichever one happens to be generating it. Over-attributing on one
// platform is harmless; omitting a module the binary links is the violation this
// tool exists to prevent.
var releaseTargets = []target{
	{goos: "linux", goarch: "amd64"},
	{goos: "linux", goarch: "arm64"},
	{goos: "darwin", goarch: "amd64"},
	{goos: "darwin", goarch: "arm64"},
}

func main() {
	out := flag.String("out", "THIRD_PARTY_LICENSES", "output path for the attribution bundle")
	pkg := flag.String("pkg", "./cmd/ofga", "package whose linked dependencies are attributed")
	flag.Parse()
	if err := run(*out, *pkg); err != nil {
		fmt.Fprintln(os.Stderr, "licensegen:", err)
		os.Exit(1)
	}
}

func run(out, pkg string) error {
	// Scoped to the binary's package rather than ./... so that build-time tools
	// under tools/, which ship to nobody, stay out of what ofga must attribute.
	var listed strings.Builder
	for _, t := range releaseTargets {
		cmd := exec.Command("go", "list", "-deps", "-f",
			"{{if not .Standard}}{{with .Module}}{{.Path}}\t{{.Version}}\t{{.Dir}}{{end}}{{end}}", pkg)
		cmd.Env = append(os.Environ(), "GOOS="+t.goos, "GOARCH="+t.goarch)
		cmd.Stderr = os.Stderr
		out, err := cmd.Output()
		if err != nil {
			return fmt.Errorf("go list for %s/%s: %w", t.goos, t.goarch, err)
		}
		listed.Write(out)
	}

	mods, err := parseModules(listed.String(), mainModule)
	if err != nil {
		return err
	}

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "%s\n\n%s\n\n%s\n\n",
		"ofga third-party licenses",
		"The ofga binary statically links the modules listed below. Each entry\n"+
			"reproduces that module's license and attribution notices, as those\n"+
			"licenses require. Generated by tools/licensegen; do not edit by hand.",
		fmt.Sprintf("Modules: %d", len(mods)))
	if err := generate(&buf, mods); err != nil {
		return err
	}

	return os.WriteFile(out, buf.Bytes(), 0o644)
}

// parseModules turns `go list -deps` output into the deduplicated set of
// dependencies to attribute, dropping the main module and any line without a
// module (standard library packages emit a bare newline).
func parseModules(out, mainModule string) ([]module, error) {
	seen := make(map[string]bool)

	var mods []module
	for _, line := range strings.Split(strings.TrimSpace(out), "\n") {
		fields := strings.Split(strings.TrimSpace(line), "\t")
		if len(fields) != 3 || fields[0] == "" || fields[0] == mainModule {
			continue
		}
		if seen[fields[0]] {
			continue
		}
		seen[fields[0]] = true

		if fields[2] == "" {
			return nil, fmt.Errorf("%s: module has no local directory; run 'go mod download'", fields[0])
		}
		mods = append(mods, module{Path: fields[0], Version: fields[1], Dir: fields[2]})
	}

	slices.SortFunc(mods, func(a, b module) int { return strings.Compare(a.Path, b.Path) })

	return mods, nil
}

// licenseFiles returns the module's license and NOTICE files, sorted by
// filename so the bundle stays byte-stable across runs. A module may carry more
// than one license (a vendored subpackage under a second license, say), and all
// of them bind.
func licenseFiles(dir string) ([]string, [][]byte, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, nil, err
	}

	var names []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		// Modules spell it LICENSE, LICENCE, LICENSE.txt/.md, COPYING, and
		// occasionally add a second file such as LICENSE.docs.
		switch upper := strings.ToUpper(e.Name()); {
		case strings.HasPrefix(upper, "LICENSE"),
			strings.HasPrefix(upper, "LICENCE"),
			strings.HasPrefix(upper, "COPYING"),
			strings.HasPrefix(upper, "NOTICE"):
			names = append(names, e.Name())
		}
	}
	slices.Sort(names)

	texts := make([][]byte, 0, len(names))
	for _, name := range names {
		text, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			return nil, nil, err
		}
		texts = append(texts, text)
	}

	return names, texts, nil
}

func generate(w io.Writer, mods []module) error {
	var out []byte
	for _, m := range mods {
		names, texts, err := licenseFiles(m.Dir)
		if err != nil {
			return fmt.Errorf("%s %s: %w", m.Path, m.Version, err)
		}
		if len(names) == 0 {
			return fmt.Errorf("%s %s: no license file found in %s", m.Path, m.Version, m.Dir)
		}

		// A module may be covered by several licenses at once, so report every
		// match rather than the first. Sorted and deduplicated because the
		// bundle is committed and diffed in CI: unstable ordering would show up
		// as spurious churn on unrelated dependency bumps.
		var ids []string
		for i, text := range texts {
			// NOTICE files travel with the bundle to satisfy Apache-2.0 4(d),
			// but they are attribution rather than license text — scanning them
			// would pick up whatever licenses they mention in prose.
			if strings.HasPrefix(strings.ToUpper(names[i]), "NOTICE") {
				continue
			}
			for _, match := range licensecheck.Scan(text).Match {
				ids = append(ids, match.ID)
			}
		}
		slices.Sort(ids)
		ids = slices.Compact(ids)

		if len(ids) == 0 {
			return fmt.Errorf("%s %s: license text in %s could not be identified", m.Path, m.Version, m.Dir)
		}
		exc := exceptions[m.Path]
		for _, id := range ids {
			if !allowed[id] && !slices.Contains(exc.ids, id) {
				return fmt.Errorf("%s %s: license %s is not on the allowlist", m.Path, m.Version, id)
			}
		}

		rule := strings.Repeat("=", 80)
		out = append(out, fmt.Sprintf("%s\n%s %s\nLicense: %s\n",
			rule, m.Path, m.Version, strings.Join(ids, ", "))...)
		if exc.reason != "" {
			out = append(out, fmt.Sprintf("Exception: %s\n", exc.reason)...)
		}
		out = append(out, rule...)
		out = append(out, '\n')
		for i, name := range names {
			out = append(out, fmt.Sprintf("\n--- %s ---\n\n%s\n", name, texts[i])...)
		}
	}

	_, err := w.Write(out)

	return err
}
